### ISSUE TITLE
check for columtype is wrong

### ISSUE THREAD

**Issue by norisk-dev** [PAYONE-GmbH/oxid-6#173]
Tag: V1.3.2
core/fcpayone_events.php:578

Should the expected value not be char32 instead of int11? Currently, as far as I can see, it does not perform the migration because of this and the column remains an int11. This caused problems with the status.php.

Greetings,
Christoph

**Comment by fjbender** [comment]
For reference: https://github.com/PAYONE-GmbH/oxid-6/blob/30d3cad7c1365d8c3fc7b5bda3281c35ef9e9f78/core/fcpayone_events.php#L578

In a test shop in our system, this also looks rather suspicious (which might be because of our outrageously long order numbers, but still):

![image](https://user-images.githubusercontent.com/7370694/89613040-988d4f80-d881-11ea-9026-93b1fa299d91.png)

I'll talk to Dev about it.
